spring:
  datasource:
    username: syswin
    password: syswin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.28.5.92:3306/temail-notification?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    platform: mysql
    continue-on-error: true
    initialization-mode: always
  redis:
    host: 192.168.0.251
    port: 7389
    database: 1
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

server:
  port: 8900
  servlet:
    context-path: /

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mapper/*Mapper.xml

#loging
logging:
  level:
    com.syswin.temail.notification.main.infrastructure: DEBUG

temail:
  notification:
    rocketmq:
      namesrvAddr: 172.28.43.18:9876
      topics:
        mailAgent: temail-usermail
#        mailAgent: service_topic
#        notify: service_topic
        notify: temail-notification