server:
  port: 8081
  servlet:
    context-path: /


temail:
  rocketmq:
    namesrvAddr: 172.28.43.18:9876
    topics:
#      service: temail-usermail
      service: service_topic
      consumer: service_topic
#      consumer: consumer_tipic